# computation
seed: 1
device: "cuda"
batch_size: 32
batch_size_eval: 32
num_workers: 6
prefetch_factor: 2
pin_mem: True
# pre-proc
input_size: 512000 #160000 # check if this is good? unlikely!
eval_overlap: 0
eval_pad: "drop" # drop, zero, overlap
compression: "PCEN"
## PCEN
pcen_learn_logs: True
## TBN
tbn_median_filter: False
tbn_median_filter_append: False
log1p_initial_a: 0
log1p_trainable: False
log1p_per_band: False
# frontend
frontend: "Mel"
## EfficientLeaf
num_groups: 4
conv_win_factor: 3
stride_factor: 1
# save and load
resume: null
overwrite_save: False
save_every: 5
# Training
start_epoch: 1
test_every_epoch: False
epochs: 100
warmup_steps: 1000
save_best_model: "auc"
model_name: "EfficientNet"
## opt
frontend_lr_factor: 1
lr: 0.001
min_lr: 1e-6
adam_eps: 1e-08
## sched
scheduler: True
scheduler_mode: "loss"
scheduler_factor: 0.1
patience: 10
# paths
data_path: "/home/ravi/Documents/kaggle/bird/birdclef-2024/data"